// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoGame.Models;

#nullable disable

namespace ProjetoGame.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20231026143304_Criacao-Nota")]
    partial class CriacaoNota
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoGame.Models.Cadastro", b =>
                {
                    b.Property<int>("CadastroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CadastroId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CadastroId"));

                    b.Property<string>("CadastroName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CadastroCategoria");

                    b.Property<string>("CadastroNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CadastroNome");

                    b.HasKey("CadastroId");

                    b.ToTable("Cadastro");
                });

            modelBuilder.Entity("ProjetoGame.Models.Descricao", b =>
                {
                    b.Property<int>("DescricaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DescricaoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DescricaoId"));

                    b.Property<int>("CadastroId")
                        .HasColumnType("int");

                    b.Property<string>("DescricaoJogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DescricaoJogo");

                    b.Property<int>("NotaId")
                        .HasColumnType("int");

                    b.HasKey("DescricaoId");

                    b.HasIndex("CadastroId");

                    b.HasIndex("NotaId");

                    b.ToTable("Descricao");
                });

            modelBuilder.Entity("ProjetoGame.Models.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NotaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NotaValor")
                        .HasColumnType("int")
                        .HasColumnName("NotaValor");

                    b.HasKey("Id");

                    b.ToTable("Nota");
                });

            modelBuilder.Entity("ProjetoGame.Models.Descricao", b =>
                {
                    b.HasOne("ProjetoGame.Models.Cadastro", "Cadastro")
                        .WithMany()
                        .HasForeignKey("CadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoGame.Models.Nota", "Nota")
                        .WithMany()
                        .HasForeignKey("NotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cadastro");

                    b.Navigation("Nota");
                });
#pragma warning restore 612, 618
        }
    }
}
